# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jordan Calder
email: jordancalder@gmail.com
description: "Writings, thoughts, and learnings of a computer geek."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jordancalder.github.io" # the base hostname & protocol for your site
twitter_username: jordankalder
github_username:  jordancalder

# Build settings
markdown: kramdown
